!=========================================================================================
! The program FLiTs (Fast Line Tracer(s)) is a line raytracer especially designed for
! protoplanetary disks. It reads in the temperature and density structure from somewhere
! else and computes the level populations of the lines either by LTE, or reads them in
! from ProDiMo.
! The program uses a single, unformatted input file which is the only argument to the
! program needed. All arguments can be changed from the command line as well by using the
! -s keyword=value syntax.
! So in principle the program is run like:
! FLiTs input.dat -s keyword=value -s keyword2=value2
! That's it, have fun!
!=========================================================================================
program FLiTs
  use InOut
  implicit none
  character(len=500) :: VersionGIT

  ! terms of use
  call output("==================================================================")
  call output("By using FLiTs you agree to the terms of use that can be found")
  call output("in the User Guide: http://www.michielmin.nl/FLiTs/UserGuide.pdf")
  call output("It basically means you offer me co-author rights on any paper")
  call output("that uses results computed with FLiTs.")

  call output("==================================================================")
  call output("Let's get the show on the road!!")
  call output("FLiTs "//trim(VersionGIT()))

  call WriteSysinfo()
  call output("==================================================================")
  call output(" ")

  ! initialization
  call Initialize()

  ! read in density, temperature, opacity, and local radiation field
  !   call ReadStructure()
  ! read in line data: which lines, Einstein coefficients of all lines
  ! setup/readin level populations
  !   call ReadLineData()

  ! read lambda files, this also defines what line species (molecules) are included for the calculations
  call ReadLambdaFiles()
  ! read in all data from the forFLiTs file generated by ProDiMo
  call ReadForFLiTs()

  ! prepare the remaining things in the structure for the raytracing and rearrange the forFLiTs data to include only the needed molecules
  call PrepareStructure()

  ! the action starts!!
  ! first setup the paths
  call SetupPaths()
  ! sort the lines by wavelength
  call SortLines()
  ! output linelist file
  call LineList()
  ! now do the continuum raytracing at the reduced spectral resolution
  call RaytraceContinuum()

  ! and now the real interesting part!!
  ! do the line raytracing
  call RaytraceLines()

  ! finally write all the output files
  !   call OutputFiles()

  ! well that's it. we seem to be done!
  ! have a good day
  call output("==================================================================")
  call output("Success!!")
  call output("Have a nice day!")
  call output("==================================================================")

end program FLiTs

