c=========================================================================================
c The program FLiTs (Fast Line Tracer(s)) is a line raytracer especially designed for 
c protoplanetary disks. It reads in the temperature and density structure from somewhere
c else and computes the level populations of the lines either by LTE, or reads them in
c from ProDiMo.
c The program uses a single, unformatted input file which is the only argument to the 
c program needed. All arguments can be changed from the command line as well by using the
c -s keyword=value syntax.
c So in principle the program is run like:
c FLiTs input.dat -s keyword=value -s keyword2=value2
c That's it, have fun!
c=========================================================================================
	program FLiTs
	IMPLICIT NONE
	character*500 VersionGIT

c terms of use
	call output("==================================================================")
	call output("By using FLiTs you agree to the terms of use that can be found")
	call output("in the User Guide: http://www.michielmin.nl/FLiTs/UserGuide.pdf")
	call output("It basically means you offer me co-author rights on any paper")
	call output("that uses results computed with FLiTs.")

	call output("==================================================================")
	call output("Let's get the show on the road!!")
	call output("FLiTs "//trim(VersionGIT()))
	call output("==================================================================")

c initialization
	call Initialize()

c read in density, temperature, opacity, and local radiation field
c	call ReadStructure()
c read in line data: which lines, Einstein coefficients of all lines
c setup/readin level populations
c	call ReadLineData()

c read in all data from the forFLiTs file generated by ProDiMo
	call ReadForFLiTs()
c read lambda files and rearrange the forFLiTs data to include only the needed molecules
	call ReadLambdaFiles()

c prepare the remaining things in the structure for the raytracing
	call PrepareStructure()
	
c the action starts!!
c first setup the paths
	call SetupPaths()
c sort the lines by wavelength
	call SortLines()
c output linelist file
	call LineList()
c now do the continuum raytracing at the reduced spectral resolution
	call RaytraceContinuum()


c and now the real interesting part!!
c do the line raytracing
	call RaytraceLines()

c finally write all the output files
c	call OutputFiles()

c well that's it. we seem to be done!
c have a good day
	call output("==================================================================")
	call output("Success!!")
	call output("Have a nice day!")
	call output("==================================================================")

	end
	
